### ISSUE TITLE
wifiphisher not working properly after install

### ISSUE THREAD

**Issue by squalldna** [wifiphisher/wifiphisher#1193]
**Version**:

> root@kali:~# git show | grep commit
> fatal: not a git repository (or any of the parent directories): .git

**Description**: 
Ive been having issues with wifiphisher after installing it on my raspberry pi 3B running Kali Linux 2019.3a, 64bit.
so my issues is during the attack whichever i choose, the victim device is not notified to connect to the fake page. the deauth works though.
2nd issue, after pressing ESC, im only stuck here:

> root@kali:~# wifiphisher
> ^[[A[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-11-01 00:01
> [+] Timezone detected. Setting channel range to 1-13
> [+] Selecting wlan1 interface for the deauthentication attack
> [+] Selecting wlan0 interface for creating the rogue Access Point
> [+] Changing wlan0 MAC addr (BSSID) to 00:00:00:ac:88:c3
> [+] Changing wlan0 MAC addr (BSSID) to 00:00:00:fe:f8:1b
> No handlers could be found for logger "wifiphisher.common.utilities"
> [*] Cleared leases, started DHCP, set up iptables
> [+] Show your support!
> [+] Follow us: https://twitter.com/wifiphisher
> [+] Like us: https://www.facebook.com/Wifiphisher
> [+] Captured credentials:

so i have to ctrl-z my way out of the script.

also, i feel like its not properly installing.

my way of installing is this:

git clone https://github.com/wifiphisher/wifiphisher.git
cd wifiphisher
sudo python setup.py install

and i also install roguehostapd when prompt to do so.

whenever i install this to a raspbian OS using the same method, im not getting any of these issues.

> root@kali:~# iw list
> Wiphy phy1
> 	max # scan SSIDs: 4
> 	max scan IEs length: 2257 bytes
> 	max # sched scan SSIDs: 0
> 	max # match sets: 0
> 	max # scan plans: 1
> 	max scan plan interval: -1
> 	max scan plan iterations: 0
> 	Retry short limit: 7
> 	Retry long limit: 4
> 	Coverage class: 0 (up to 0m)
> 	Supported Ciphers:
> 		* WEP40 (00-0f-ac:1)
> 		* WEP104 (00-0f-ac:5)
> 		* TKIP (00-0f-ac:2)
> 		* CCMP-128 (00-0f-ac:4)
> 		* CCMP-256 (00-0f-ac:10)
> 		* GCMP-128 (00-0f-ac:8)
> 		* GCMP-256 (00-0f-ac:9)
> 		* CMAC (00-0f-ac:6)
> 		* CMAC-256 (00-0f-ac:13)
> 		* GMAC-128 (00-0f-ac:11)
> 		* GMAC-256 (00-0f-ac:12)
> 	Available Antennas: TX 0 RX 0
> 	Supported interface modes:
> 		 * managed
> 		 * monitor
> 	Band 1:
> 		Capabilities: 0x17e
> 			HT20/HT40
> 			SM Power Save disabled
> 			RX Greenfield
> 			RX HT20 SGI
> 			RX HT40 SGI
> 			RX STBC 1-stream
> 			Max AMSDU length: 3839 bytes
> 			No DSSS/CCK HT40
> 		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
> 		Minimum RX AMPDU time spacing: 2 usec (0x04)
> 		HT TX/RX MCS rate indexes supported: 0-7, 32
> 		Bitrates (non-HT):
> 			* 1.0 Mbps (short preamble supported)
> 			* 2.0 Mbps (short preamble supported)
> 			* 5.5 Mbps (short preamble supported)
> 			* 11.0 Mbps (short preamble supported)
> 			* 6.0 Mbps
> 			* 9.0 Mbps
> 			* 12.0 Mbps
> 			* 18.0 Mbps
> 			* 24.0 Mbps
> 			* 36.0 Mbps
> 			* 48.0 Mbps
> 			* 54.0 Mbps
> 		Frequencies:
> 			* 2412 MHz [1] (20.0 dBm)
> 			* 2417 MHz [2] (20.0 dBm)
> 			* 2422 MHz [3] (20.0 dBm)
> 			* 2427 MHz [4] (20.0 dBm)
> 			* 2432 MHz [5] (20.0 dBm)
> 			* 2437 MHz [6] (20.0 dBm)
> 			* 2442 MHz [7] (20.0 dBm)
> 			* 2447 MHz [8] (20.0 dBm)
> 			* 2452 MHz [9] (20.0 dBm)
> 			* 2457 MHz [10] (20.0 dBm)
> 			* 2462 MHz [11] (20.0 dBm)
> 			* 2467 MHz [12] (20.0 dBm) (no IR)
> 			* 2472 MHz [13] (20.0 dBm) (no IR)
> 			* 2484 MHz [14] (20.0 dBm) (no IR)
> 	Supported commands:
> 		 * new_interface
> 		 * set_interface
> 		 * new_key
> 		 * start_ap
> 		 * new_station
> 		 * new_mpath
> 		 * set_mesh_config
> 		 * set_bss
> 		 * authenticate
> 		 * associate
> 		 * deauthenticate
> 		 * disassociate
> 		 * join_ibss
> 		 * join_mesh
> 		 * set_tx_bitrate_mask
> 		 * frame
> 		 * frame_wait_cancel
> 		 * set_wiphy_netns
> 		 * set_channel
> 		 * set_wds_peer
> 		 * probe_client
> 		 * set_noack_map
> 		 * register_beacons
> 		 * start_p2p_device
> 		 * set_mcast_rate
> 		 * connect
> 		 * disconnect
> 		 * set_qos_map
> 		 * set_multicast_to_unicast
> 	Supported TX frame types:
> 		 * IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
> 		 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
> 		 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
> 		 * AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
> 		 * mesh point: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
> 		 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
> 		 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
> 		 * P2P-device: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
> 	Supported RX frame types:
> 		 * IBSS: 0x40 0xb0 0xc0 0xd0
> 		 * managed: 0x40 0xd0
> 		 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
> 		 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
> 		 * mesh point: 0xb0 0xc0 0xd0
> 		 * P2P-client: 0x40 0xd0
> 		 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
> 		 * P2P-device: 0x40 0xd0
> 	software interface modes (can always be added):
> 		 * monitor
> 	interface combinations are not supported
> 	HT Capability overrides:
> 		 * MCS: ff ff ff ff ff ff ff ff ff ff
> 		 * maximum A-MSDU length
> 		 * supported channel width
> 		 * short GI for 40 MHz
> 		 * max A-MPDU length exponent
> 		 * min MPDU start spacing
> 	Device supports TX status socket option.
> 	Device supports HT-IBSS.
> 	Device supports SAE with AUTHENTICATE command
> 	Device supports low priority scan.
> 	Device supports scan flush.
> 	Device supports AP scan.
> 	Device supports per-vif TX power setting
> 	Driver supports full state transitions for AP/GO clients
> 	Driver supports a userspace MPM
> 	Device supports active monitor (which will ACK incoming frames)
> 	Device supports configuring vdev MAC-addr on create.
> 	Supported extended features:
> 		* [ RRM ]: RRM
> 		* [ FILS_STA ]: STA FILS (Fast Initial Link Setup)
> 		* [ CQM_RSSI_LIST ]: multiple CQM_RSSI_THOLD records
> 		* [ CONTROL_PORT_OVER_NL80211 ]: control port over nl80211
> Wiphy phy0
> 	max # scan SSIDs: 10
> 	max scan IEs length: 2048 bytes
> 	max # sched scan SSIDs: 16
> 	max # match sets: 16
> 	max # scan plans: 1
> 	max scan plan interval: 508
> 	max scan plan iterations: 0
> 	Retry short limit: 7
> 	Retry long limit: 4
> 	Coverage class: 0 (up to 0m)
> 	Device supports roaming.
> 	Device supports T-DLS.
> 	Supported Ciphers:
> 		* WEP40 (00-0f-ac:1)
> 		* WEP104 (00-0f-ac:5)
> 		* TKIP (00-0f-ac:2)
> 		* CCMP-128 (00-0f-ac:4)
> 	Available Antennas: TX 0 RX 0
> 	Supported interface modes:
> 		 * IBSS
> 		 * managed
> 		 * AP
> 		 * monitor
> 		 * P2P-client
> 		 * P2P-GO
> 		 * P2P-device
> 	Band 1:
> 		Capabilities: 0x1020
> 			HT20
> 			Static SM Power Save
> 			RX HT20 SGI
> 			No RX STBC
> 			Max AMSDU length: 3839 bytes
> 			DSSS/CCK HT40
> 		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
> 		Minimum RX AMPDU time spacing: 16 usec (0x07)
> 		HT TX/RX MCS rate indexes supported: 0-7
> 		Bitrates (non-HT):
> 			* 1.0 Mbps
> 			* 2.0 Mbps (short preamble supported)
> 			* 5.5 Mbps (short preamble supported)
> 			* 11.0 Mbps (short preamble supported)
> 			* 6.0 Mbps
> 			* 9.0 Mbps
> 			* 12.0 Mbps
> 			* 18.0 Mbps
> 			* 24.0 Mbps
> 			* 36.0 Mbps
> 			* 48.0 Mbps
> 			* 54.0 Mbps
> 		Frequencies:
> 			* 2412 MHz [1] (20.0 dBm)
> 			* 2417 MHz [2] (20.0 dBm)
> 			* 2422 MHz [3] (20.0 dBm)
> 			* 2427 MHz [4] (20.0 dBm)
> 			* 2432 MHz [5] (20.0 dBm)
> 			* 2437 MHz [6] (20.0 dBm)
> 			* 2442 MHz [7] (20.0 dBm)
> 			* 2447 MHz [8] (20.0 dBm)
> 			* 2452 MHz [9] (20.0 dBm)
> 			* 2457 MHz [10] (20.0 dBm)
> 			* 2462 MHz [11] (20.0 dBm)
> 			* 2467 MHz [12] (disabled)
> 			* 2472 MHz [13] (disabled)
> 			* 2484 MHz [14] (disabled)
> 	Supported commands:
> 		 * new_interface
> 		 * set_interface
> 		 * new_key
> 		 * start_ap
> 		 * join_ibss
> 		 * set_pmksa
> 		 * del_pmksa
> 		 * flush_pmksa
> 		 * remain_on_channel
> 		 * frame
> 		 * set_wiphy_netns
> 		 * set_channel
> 		 * tdls_oper
> 		 * start_sched_scan
> 		 * start_p2p_device
> 		 * connect
> 		 * disconnect
> 		 * crit_protocol_start
> 		 * crit_protocol_stop
> 		 * update_connect_params
> 	Supported TX frame types:
> 		 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
> 		 * monitor: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
> 		 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
> 		 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
> 		 * P2P-device: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
> 	Supported RX frame types:
> 		 * managed: 0x40 0xd0
> 		 * monitor: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
> 		 * P2P-client: 0x40 0xd0
> 		 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
> 		 * P2P-device: 0x40 0xd0
> 	software interface modes (can always be added):
> 	valid interface combinations:
> 		 * #{ managed } <= 1, #{ monitor } <= 1, #{ P2P-device } <= 1, #{ P2P-client, P2P-GO } <= 1,
> 		   total <= 4, #channels <= 2
> 		 * #{ managed } <= 1, #{ AP } <= 1, #{ monitor } <= 1, #{ P2P-client } <= 1, #{ P2P-device } <= 1,
> 		   total <= 5, #channels <= 1
> 	Device supports scan flush.
> 	Device supports randomizing MAC-addr in sched scans.
> 	Supported extended features:
> 
> 
> wlan0     IEEE 802.11  ESSID:off/any  
>           Mode:Managed  Access Point: Not-Associated   
>           Retry short limit:7   RTS thr:off   Fragment thr:off
>           Encryption key:off
>           Power Management:on
>           
> wlan1     IEEE 802.11  ESSID:off/any  
>           Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
>           Retry short limit:7   RTS thr:off   Fragment thr:off
>           Encryption key:off
>           Power Management:off
>           
> eth0      no wireless extensions.
> 
> lo        no wireless extensions.

**Comment by sophron** [comment]
Hi,

Please update to the latest revision and try again. I pushed a commit that fixes this.

**Comment by squalldna** [comment]
I reinstalled. Now it's asking me to use python 3 to install wifiphisher. This is after cd wifiphisher.

> 
>
> > Linux kali 4.19.81-Re4son-v8+ #1 SMP PREEMPT Wed Nov 6 03:33:03 UTC 2019 aarch64
> 
> The programs included with the Kali GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Kali GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
> Last login: Sun Dec 15 09:15:44 2019 from 192.168.1.80
> root@kali:~# cd wifiphisher/
> root@kali:~/wifiphisher# python setup.py install                                                  Please use Python 3 to install Wifiphisher.
> root@kali:~/wifiphisher# python3 setup.py install
> /tmp/tmp_netlink_jhv0_w_p/test_netlink.c:2:10: fatal error: netlink/netlink.h: No such file or directory
>     2 | #include <netlink/netlink.h>
>       |          ^~~~~~~~~~~~~~~~~~~
> compilation terminated.
> The development package for netlink is required for the compilation of roguehostapd. Please install it and rerun the script (e.g. on Debian-based systems run: apt-get install libnl-3-dev libnl-genl-3-dev
> root@kali:~/wifiphisher#


I dont know why my reply have lines in it. Sorry.

**Comment by squalldna** [comment]
I installed the two programs. Still getting the error.but now it wants me to install a new package libssl-dev.

**Comment by squalldna** [comment]
> I installed the two programs. Still getting the error.but now it wants me to install a new package libssl-dev.

Installation worked. I'll give update.
