### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'Thread-7'.

### ISSUE THREAD

**Issue by ghost** [wifiphisher/wifiphisher#1275]
Exception in thread Thread-7:                                                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                                                
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner                                                                                                                                           
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/wifiphisher/common/phishinghttp.py", line 199, in runHTTPServer
    app.listen(port, address=ip)
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/usr/lib/python3/dist-packages/tornado/tcpserver.py", line 144, in listen
    self.add_sockets(sockets)
  File "/usr/lib/python3/dist-packages/tornado/tcpserver.py", line 158, in add_sockets
    sock, self._handle_connection)
  File "/usr/lib/python3/dist-packages/tornado/netutil.py", line 229, in add_accept_handler
    io_loop = IOLoop.current()
  File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 282, in current
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-7'.

**Comment by zoben10** [comment]
Hello, I have the same problem. Did you find any help? 

![image](https://user-images.githubusercontent.com/61861342/76056482-b2c6a880-5f44-11ea-8e75-102939263483.png)

**Comment by zoben10** [comment]
Hello, I found the solution. Follow these steps:

$ `sudo apt-get remove wifiphisher`
$ `git clone https://github.com/wifiphisher/wifiphisher.git`
$ `cd wifiphisher`
$ `sudo apt-get install libnl-3-dev libnl-genl-3-dev`
$ `sudo python3 setup.py install`

It should work with no error now.

**Comment by newtonsart** [comment]
Same problem, but i use arch and I tried everything i could.

**Comment by sophron** [comment]
I just merged #1234 that fixes this. Please update to the latest revision and run the tool again.

**Comment by scorpio-war** [comment]
I've faced the same problem on latest kali 2020.2 release. Firstly I've tried to install wifiphisher via apt-get, then as described in previous zoben10 post. But problem still remains in both cases. Please, help me, how to solve it.

**Comment by sophron** [comment]
This should be fixed. @scorpio-war open a new issue if needed.
