### ISSUE TITLE
Access point selection showing power as 0% for all access points

### ISSUE THREAD

**Issue by kn0wledge** [wifiphisher/wifiphisher#478]
Just did a fresh clone and fresh install of wifiphisher after the latest merge of the redesign. For some reason , power shows as 0% for all APs

**Comment by blackHatMonkey** [comment]
@kn0wledge would you be able to get a screen shot of it?

**Comment by kn0wledge** [comment]
![screenshot from 2017-03-01 15-55-55](https://cloud.githubusercontent.com/assets/25384952/23481234/bc2020c4-fe98-11e6-8829-a1850e8c9d20.png)
here you go

**Comment by kn0wledge** [comment]
@blackHatMonkey any ideas on how to trouble shoot this?

**Comment by blackHatMonkey** [comment]
@kn0wledge I will take a look at it and let you know :smile:.

**Comment by sophron** [comment]
A network dump would be useful here. Try `tcpdump -i <interface> -s 65535 -w out.pcap` where <interface> is the `AP` interface chosen by `wifiphisher`.

You can send the `out.pcap` file to @blackHatMonkey afterwards and he'll be able to open it in Wireshark and find out if the RSSI field of beacon frames are there.

**Comment by blackHatMonkey** [comment]
@kn0wledge @sophron I was able to reproduce the bug with the latest `kali`. I had to install a fresh version of `kali` to make sure it was not just my system.

**Comment by blackHatMonkey** [comment]
@kn0wledge #480 has been merged. Let me know if you still experience this bug :smile:.

**Comment by kn0wledge** [comment]
@blackhatmonkey that fixed it ! Thx ! That was quick!

**Comment by blackHatMonkey** [comment]
I still see power as 0%.

**Comment by blackHatMonkey** [comment]
@anakin1028 would you be able to look into this as well?

**Comment by ukscone** [comment]
I have this problem with tp-link 722wn for both wifiphisher & wash on kali rolling. airodump-ng shows the power levels and all my other wifi dongles (edimax, pau05, noname ) show power levels in both wifiphisher and wash. so far i'm flummuxed as to why and if anyone has any ideas i'd be grateful

**Comment by anakin1028** [comment]
@blackHatMonkey ,
I haven't seen this bug in my office environment. I'll try to reproduce it.

**Comment by anakin1028** [comment]
@blackHatMonkey do you have screenshot for the power 0 and the sniffer mapping for that?

**Comment by blackHatMonkey** [comment]
@anakin1028 I will try to get it using `pdb`.

**Comment by sophron** [comment]
@blackHatMonkey I believe a network dump would be more helpful. Check my first post on this thread.

**Comment by JetseVerschuren** [comment]
Tou said 

> A network dump would be useful here. Try tcpdump -i <interface> -s 65535 -w out.pcap where <interface> is the AP interface chosen by Wifiphisher. Do that while Wifiphisher is showing the nearby APs.

I think you meant the `Monitor Mode` interface because the `AP` interface is hosting a network not listening for networks.

**Comment by blackHatMonkey** [comment]
[Here](http://www.filedropper.com/out_2) is a the `tcpdump`. The power is 0% for all access points.

**Comment by blackHatMonkey** [comment]
Here is some more information:
```bash
(Pdb)) rssi
-256
((Pdb)) packet  
<RadioTap  version=0 pad=0 len=36 present=TSFT+Flags+Rate+Channel+dBm_AntSignal+b14+b29+Ext notdecoded=' \x08\x00\x00\x00\x00\x00\x00\xack\x9a\xdd\x01\x00\x00\x00\x10\x02q\t\xa0\x00\xc0\x00\x00\x00\xc0\x00' |<Dot11  subtype=8L type=Management proto=0L FCfield= ID=0 addr1=ff:ff:ff:ff:ff:ff addr2=f0:f2:49:44:3f:48 addr3=f0:f2:49:44:3f:48 SC=34784 addr4=None |<Dot11Beacon  timestamp=1714864333184 beacon_interval=100 cap=short-slot+ESS+privacy+short-preamble |<Dot11Elt  ID=SSID len=11 info='Rogers22253' |<Dot11Elt  ID=Rates len=8 info='\x82\x84\x8b\x96\x8c\x12\x98$' |<Dot11Elt  ID=DSset len=1 info='\x01' |<Dot11Elt  ID=TIM len=4 info='\x00\x02\x00\x00' |<Dot11Elt  ID=7 len=6 info='US \x01\x0b\x1e' |<Dot11Elt  ID=ERPinfo len=1 info='\x00' |<Dot11Elt  ID=ESRates len=4 info='\xb0H`l' |<Dot11Elt  ID=45 len=26 info='\xad\x01\x1b\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x04\x06\xe6G\r\x00' |<Dot11Elt  ID=61 len=22 info='\x01\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' |<Dot11Elt  ID=127 len=8 info='\x00\x00\x00\x00\x00\x00\x00@' |<Dot11Elt  ID=vendor len=24 info="\x00P\xf2\x02\x01\x01\x80\x00\x03\xa4\x00\x00'\xa4\x00\x00BC^\x00b2/\x00" |<Dot11Elt  ID=vendor len=9 info='\x00\x03\x7f\x01\x01\x00\x00\xff\x7f' |<Dot11Elt  ID=RSNinfo len=24 info='\x01\x00\x00\x0f\xac\x02\x02\x00\x00\x0f\xac\x04\x00\x0f\xac\x02\x01\x00\x00\x0f\xac\x02\x0c\x00' |<Dot11Elt  ID=vendor len=26 info='\x00P\xf2\x01\x01\x00\x00P\xf2\x02\x02\x00\x00P\xf2\x04\x00P\xf2\x02\x01\x00\x00P\xf2\x02' |<Dot11Elt  ID=vendor len=34 info='\x00P\xf2\x04\x10J\x00\x01\x10\x10D\x00\x01\x02\x10W\x00\x01\x01\x10<\x00\x01\x01\x10I\x00\x06\x007*\x00\x01 ' |<Dot11Elt  ID=217 len=99 info='\xcfu' |>>>>>>>>>>>>>>>>>>>

((Pdb)) packet.summary()
"RadioTap / 802.11 Management 8L f0:f2:49:44:3f:48 > ff:ff:ff:ff:ff:ff / Dot11Beacon / SSID='Rogers22253' / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt"

((Pdb)) packet.notdecoded[-4:-3]
'\x00'

((Pdb)) ord(packet.notdecoded[-4:-3])
0
```

Furthermore the issue is not limited to `TP-Link TL-WN722N` as some users reported. I have also tested it with `Alfa AWUS036NHA` as well with same result.

**Comment by blackHatMonkey** [comment]
After a bit more testing I could get the following
```bash
>>> a[1].summary()
"RadioTap / 802.11 Management 8L 10:be:f5:d3:9e:f4 > ff:ff:ff:ff:ff:ff / Dot11Beacon / SSID='Pookie-2GHZ' / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt / Dot11Elt"

>>> -(256 - ord(a[1].notdecoded[-2:-1]))
-81
```

which seems to be correct since the access point is close to my location and hence the higher `rssi` value.

Source: http://stackoverflow.com/questions/10818661/scapy-retrieving-rssi-from-wifi-packets

**Comment by anakin1028** [comment]
@blackHatMonkey, thanks for sharing, this is really helpful to clarify this problem.
After seeing the sniffer given by Brian, the problem is that the radiotap format is not consistent by different adapters[the one used to sniff]:

here is the snapshot I took from the pcap file from Brian:
As you can see the frames add four more bytes paddings.

![2](https://cloud.githubusercontent.com/assets/6182530/25368899/a150ef2c-29b2-11e7-9de6-cb06fb2a3eda.png)

And this can be mapping to the pdb info given by Brian:
![4](https://cloud.githubusercontent.com/assets/6182530/25369174/a6951f74-29b4-11e7-8812-61adbd7b0e58.png)

And from my sniffer and maybe for @kn0wledge 's case on the thread#478: 
There is no padding and the current wifiphisher-1.3 will correctly output the rssi

![3](https://cloud.githubusercontent.com/assets/6182530/25369034/6a7f62f2-29b3-11e7-8111-5de7a852f06d.png)

The problem is that radiotap will request a boundary alignment, so in Brian's case, the radiotap will pad four bytes and following is the MAC timestamp.

A quick fixed method maybe:
       `max(ord(pkt.notdecoded[-4:-3]), ord(pkt.notdecoded[-2:-1]))`

Since Scapy does not give us the padding information so we cannot correctly unpack the present fields if the radiotap headers contain paddings.

**Comment by sophron** [comment]
Nice analysis @anakin1028!

We can probably calculate the exact position of the RSSI value by getting the header length and parsing all fields. This may be too much for now though.

I'm okay with your solution. If we see that users are still experiencing issues, we can consider parsing the header properly.

If you create a Pull Request, I will merge it today.

**Comment by sophron** [comment]
@JetseVerschuren Yes, that's what I meant. Thanks.

**Comment by anakin1028** [comment]
@sophron, I am not sure if it is possible to parse the `pkt.notdecoded` since the present fields in the scapy packet only contains the used fields. We know each fields size, so if there is no padding in the header we can parse the notdecoded fields, but if there is paddings in the header, I thinks it no ways to parse it correctly. 

Like the following parser project, it cannot works with the padding case.
https://github.com/azz2k/scapy-rssi

**Comment by sophron** [comment]
Have a look at this <a href="https://github.com/ivanlei/airodump-iv/blob/master/airoiv/scapy_ex.py#L102">one</a> here. It seems to remove any padding data after parsing the values.

**Comment by anakin1028** [comment]
Cool thanks!

**Comment by blackHatMonkey** [comment]
This has been fixed with the latest updates.

**Comment by ajohnson8492** [comment]
Hello. I recently downloaded and attempted to use Wifiphisher and I'm encountering this error. 
![0 pwr for wifiphsher  ](https://user-images.githubusercontent.com/59505169/71786537-6f020200-2fda-11ea-8061-8ea845d899a0.png)

I did some research and implemented the fix as outlined in fix(recon): fix a bug where access point power reported as 0% #480
![fix(recon)- fix a bug where access point power reported as 0% #480](https://user-images.githubusercontent.com/59505169/71786568-ab356280-2fda-11ea-98ca-88b7ea54ade9.png)

I installed wifiphisher using the following method as outlined in the manual:

git clone https://github.com/wifiphisher/wifiphisher.git # Download the latest revision
cd wifiphisher # Switch to tool's directory
sudo python setup.py install # Install any dependencies

If you need any more other information please let me know. I'm new to this and want to get it to work.

**Comment by hdawg12** [comment]
i'm still having this issue. Do I need to go into recon.py and add this code in? 
Thanks

**Comment by JetseVerschuren** [comment]
It looks like it's already in master. See [recon.py](https://github.com/wifiphisher/wifiphisher/blob/f0be7838b5c39855aa7a1f6b70566e69ad2f4334/wifiphisher/common/recon.py#L109)

**Comment by hdawg12** [comment]
"# find the signal strength
        rssi = get_rssi(packet.notdecoded)
        new_signal_strength = calculate_signal_strength(rssi)"
this is whats in the master.  I don't think its been added.  I will try adding it and seeing if that resolve my issue.

**Comment by RasmusGodske** [comment]
I'm still having the same problem using my Alfa Network AWUS036NHA - AR9271L Atheros Chipset
