### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by princejacob** [wifiphisher/wifiphisher#753]
when i run script after installing  i get this error 
```
root@anonpirate:/# wifiphisher
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/setuptools-27.3.0.post20170510-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/setuptools-27.3.0.post20170510-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/setuptools-27.3.0.post20170510-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "/usr/local/lib/python2.7/dist-packages/setuptools-27.3.0.post20170510-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 18, in <module>
    import wifiphisher.common.extensions as extensions
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/extensions.py", line 9, in <module>
    import scapy.layers.dot11 as dot11
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/dot11.py", line 12, in <module>
    from scapy.packet import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 39
    class Packet(BasePacket, metaclass = Packet_metaclass):
                                       ^
SyntaxError: invalid syntax
```

Edited by @blackhatmonkey: fixed the error section.

**Comment by blackHatMonkey** [comment]
@princejacob Can you remove this and install it again?

**Comment by sophron** [comment]
It looks like the `packet.py` file of Scapy was modified. Reinstallation of scapy should fix this.

**Comment by princejacob** [comment]
@blackHatMonkey  @sophron  i did reinstall ... still facing issue ..on kali but working almost fine on ubuntu

**Comment by blackHatMonkey** [comment]
@princejacob Can you try the following commands:
```bash
sudo pip2 uninstall scapy wifiphisher
sudo pip2 install scapy
git clone https://github.com/wifiphisher/wifiphisher.git && cd wifiphisher
sudo python2 bin/wifiphisher
```

**Comment by blackHatMonkey** [comment]
@princejacob I'm closing this issue due to inactivity. Feel free to re-open if needed 😄.

**Comment by christmex** [comment]
i my case like that, i cant open my wifiphiser

Traceback (most recent call last):
  File "wifiphisher", line 16, in <module>
    
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 20, in <module>
    import wifiphisher.common.extensions as extensions
  File "/root/wifiphisher/wifiphisher/common/extensions.py", line 11, in <module>
    import scapy.layers.dot11 as dot11
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/dot11.py", line 12, in <module>
    from scapy.packet import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 39
    class Packet(BasePacket, metaclass = Packet_metaclass):
                                       ^
SyntaxError: invalid syntax


how to fix it. please help

**Comment by anakin1028** [comment]
Have you tried the commands listed above?

**Comment by christmex** [comment]
@anakin1028 , done , but i get same 

this 
=============================================

Traceback (most recent call last):
  File "bin/wifiphisher", line 16, in <module>
    from wifiphisher.pywifiphisher import run
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 20, in <module>
    import wifiphisher.common.extensions as extensions
  File "/root/wifiphisher/wifiphisher/common/extensions.py", line 11, in <module>
    import scapy.layers.dot11 as dot11
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/dot11.py", line 12, in <module>
    from scapy.packet import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 39
    class Packet(BasePacket, metaclass = Packet_metaclass):
                                       ^
SyntaxError: invalid syntax
============================================================


how to repair , im so confuse , please help

**Comment by Hushang123** [comment]
Same problem here 
root@kali:~/wifiphisher/bin# wifiphisher
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 20, in <module>
    import wifiphisher.common.extensions as extensions
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/extensions.py", line 11, in <module>
    import scapy.layers.dot11 as dot11
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/dot11.py", line 12, in <module>
    from scapy.packet import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 39
    class Packet(BasePacket, metaclass = Packet_metaclass):
                                       ^
SyntaxError: invalid syntax

How am i supposed to fix this? any help will be appreciated

**Comment by anakin1028** [comment]
Can you post the output on the terminal by the following command:
```
sudo scapy
```
Since scapy doesn't do the backward compatibility well, I guess it is due to the version of module is not consistent with our supposed version.

**Comment by Hushang123** [comment]
root@kali:~# sudo scapy
Traceback (most recent call last):
  File "/usr/local/bin/scapy", line 23, in <module>
    from scapy.main import interact
  File "/usr/local/lib/python2.7/dist-packages/scapy/main.py", line 16, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/scapy/utils.py", line 129
    print("%04x  " % i,end = " ")
                           ^
SyntaxError: invalid syntax

**Comment by anakin1028** [comment]
It looks like scapy has some problem. Can you do the following?
```
pip uninstall scapy
apt-get install scapy
```

**Comment by Hushang123** [comment]
when i run "pip uninstall scapy" it shows:

root@kali:~# pip uninstall scapy
Not uninstalling scapy at /usr/lib/python2.7/dist-packages, outside environment /usr

but when installing it mentions already in the newest version

**Comment by AgeOfMarcus** [comment]
@Hushang123 i got the same error but i did 
'apt remove python-scapy'
Instead and it worked.

**Comment by anakin1028** [comment]
cool! @AgeOfMarcus do you figure out the root cause?

**Comment by SummerBalin** [comment]
Same problem here

Traceback (most recent call last):
  File "bin/wifiphisher", line 16, in <module>
    from wifiphisher.pywifiphisher import run
  File "/mnt/d/study/wifiphisher-1.4/wifiphisher/pywifiphisher.py", line 23, in <module>
    import wifiphisher.common.phishinghttp as phishinghttp
  File "/mnt/d/study/wifiphisher-1.4/wifiphisher/common/phishinghttp.py", line 3, in <module>
    from tornado.escape import json_decode
  File "/usr/local/lib/python2.7/dist-packages/tornado-6.0a1-py2.7-linux-x86_64.egg/tornado/escape.py", line 43
    def xhtml_escape(value: Union[str, bytes]) -> str:
                          ^
SyntaxError: invalid syntax

Have tried these commands：
pip uninstall scapy
apt-get install scapy

**Comment by gpotter2** [comment]
Hi, a Scapy maintainer here.
FTR: the versions packaged on most platforms are slow to follow the pip versions. You’ll probably fix such issues if you use 2.4.2+ (even 2.4.0 but it’s a bit old now), which have full Python 2&3 support.

It’s recommanded to only use `pip install scapy` (`--pre` can also be useful: currently 2.4.2 might fail to install on some platforms)
