### ISSUE TITLE
Can't grant victim internet access

### ISSUE THREAD

**Issue by asciiterminal** [wifiphisher/wifiphisher#848]
> after multiple tries i can get my victim to connect to the fake AP but can't seem to browse the internet;
> i have tried

 `wifiphisher -iI eth0 -e hi` and this is what i got
```
[*] Starting Wifiphisher 1.4 ( https://wifiphisher.org ) at 2018-01-19 16:19
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan2 interface for creating the rogue Access Point
[+] Changing wlan2 MAC addr (BSSID) to 00:00:00:a2:f3:62
[+] Changing wlan1 MAC addr to 00:00:00:e4:c8:1c
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting OAuth Login Page template
[*] S
```

> And no internet connection

> then i tried 

 
`wifiphisher -iI wlan0 -e hi`
`
[*] Starting Wifiphisher 1.4 ( https://wifiphisher.org ) at 2018-01-19 16:37
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:86:8d:28
[+] Changing wlan1 MAC addr to 00:00:00:e3:cd:8f
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting OAuth Login Page template
[*] Starting the fake access point...
[!] hostapd failed to lunch!
[+] Captured credentials:
[!] Closing

> Then i tried

`
`wifiphisher -iI wlan1 -e hi`
`
[*] Starting Wifiphisher 1.4 ( https://wifiphisher.org ) at 2018-01-19 16:38
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:be:38:0a
[+] Changing wlan1 MAC addr to 00:00:00:89:f1:ab
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting OAuth Login Page template
[*] Starting the fake access point...
[!] hostapd failed to lunch! 
[+] Captured credentials:
[!] Closing
`

> and by the way my `ifconfig` result is 

`
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.120  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::e584:c96b:87df:bd85  prefixlen 64  scopeid 0x20<link>
        ether 00:e0:4c:53:44:58  txqueuelen 1000  (Ethernet)
        RX packets 471  bytes 49284 (48.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 360  bytes 227480 (222.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 212  bytes 15996 (15.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 212  bytes 15996 (15.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.111  netmask 255.255.255.0  broadcast 192.168.1.255
        ether 74:29:af:6a:20:31  txqueuelen 1000  (Ethernet)
        RX packets 198  bytes 26866 (26.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 41  bytes 5133 (5.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.106  netmask 255.255.255.0  broadcast 192.168.1.255
        ether f8:d1:11:60:2c:2e  txqueuelen 1000  (Ethernet)
        RX packets 211  bytes 28065 (27.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18  bytes 2484 (2.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
`

> then i went for the plain attack

`wifiphisher`

> everything went normal but still when i connected the victim to the fake AP instead of creating one there was still no internet access  and yes `wlan1` is TP-LINK 722N and does monitor mode

then i tried 
`wifiphisher -iI eth0 -aI wlan0 -e hi `
```
[*] Starting Wifiphisher 1.4 ( https://wifiphisher.org ) at 2018-01-19 16:47
[-] --apinterface (-aI) and --extensionsinterface (-eI)(or --noextensions (-nE)) are used in conjuction.

 i am now hopeless 
```

**Comment by anakin1028** [comment]
Can you try to use this command first:

`wifiphisher -iI wlan1 -nE` that is to choose the ssid manually and I will check if there is big for `-e` option.

**Comment by anakin1028** [comment]
@asciiterminal this bug should be fixed in the newest commit. Can you have a try for this fix?

**Comment by asciiterminal** [comment]
@anakin1028 i tried `wifiphisher -iI wlan1 -nE -e wifi` and still no luck

**Comment by asciiterminal** [comment]
@anakin1028 i tried `wifiphisher -iI wlan1 -nE -e wifi` and still no luck

**Comment by anakin1028** [comment]
Do you pull the latest commit?

**Comment by asciiterminal** [comment]
@anakin1028  i am new to github so can you tell what means "latest commit"?

**Comment by anakin1028** [comment]
You can do the following under the wifiphisher folder:
```
git fetch
git merge origin master
```

**Comment by asciiterminal** [comment]
this is what i got
`root@kali:~/wifiphisher# git fetch
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 10 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (10/10), done.
From https://github.com/wifiphisher/wifiphisher
   a6478a3..7da8f3f  master     -> origin/master
root@kali:~/wifiphisher# git merge origin master
Updating a6478a3..7da8f3f
Fast-forward
 wifiphisher/common/extensions.py | 12 +++++-------
 wifiphisher/common/opmode.py     |  3 ++-
 2 files changed, 7 insertions(+), 8 deletions(-)
`

**Comment by anakin1028** [comment]
yes, this means the files are get updated. Can you run wifiphisher again by `python bin/wifiphisher` and see if the error get fixed?

**Comment by asciiterminal** [comment]
i figured to run the program but again when the program start it tells me that hostapd failed to lunch 
so when i delete and re-install hostapd it works but then again it fails to launch

**Comment by anakin1028** [comment]
I will take a look for this phishing scenario. Is tool work ok for you for other phishing scenarios?

**Comment by anakin1028** [comment]
Should be fixed now. You can pull the newest commit as before and try to run again:)

**Comment by asciiterminal** [comment]
The scenerios are working good just a problem with the hostapd failing at times and the payload uploading problem other than that its a fantastic app bro its far better than airbase-ng where your Access Point drops connections

**Comment by anakin1028** [comment]
Thanks:) You can just re-download or git clone wifiphisher and the payload update problem should be fixed.

**Comment by asciiterminal** [comment]
my payload is on my desktop with the name of 'update.exe' how do i set it up for the victim

**Comment by sophron** [comment]
The software will ask you to provide the path of the malicious file.
